name: Run Python Script

on:
  # Choose when to trigger the workflow
  schedule:
    - cron: '30 9 * * *'  # Runs at 9:30 AM UTC, which is 5:30 AM Eastern Time during daylight saving time
  # Optional: manual trigger
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install Kerberos dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libkrb5-dev
        
    - name: Install dependencies individually
      run: |
        python -m pip install --upgrade pip
        # Install packages one by one to better manage dependencies
        pip install --upgrade numpy==1.24.2 
        pip install gssapi==1.9.0
        pip install arcgis==2.2.0
        pip install pandas==2.0.3
        pip install pyarrow==13.0.0
        pip install requests==2.26.0
        pip install fiona==1.9.4
        pip install geopandas==0.13.2
        # List installed packages for debugging
        pip list
        
    - name: Run script
      env:
        ARCGIS_CLIENT_ID: ${{ secrets.ARCGIS_CLIENT_ID }}
        ARCGIS_CLIENT_SECRET: ${{ secrets.ARCGIS_CLIENT_SECRET }}
        ARCGIS_FEATURE_LAYER_ID: ${{ secrets.ARCGIS_FEATURE_LAYER_ID }}
      run: |
        python Crash-Injury-Dashboard-Backend.py
    
    - name: Set up Git for frontend repo
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Clone frontend repo
      run: |
        git clone https://x-access-token:${{ secrets.FRONTEND_REPO_PAT }}@github.com/rafaelmorenoco/Crash-Injury-Dashboard-Frontend.git frontend

    - name: Copy parquet file to frontend repo
      run: |
        cp crashes.parquet frontend/
        cd frontend
        git add crashes.parquet
        git commit -m "Update crashes.parquet data [skip ci]" || echo "No changes to commit"
        git push
